### PR TITLE
https://github.com/zalando/innkeeper/issues/93: Include scm-source.js…

### PR DESCRIPTION
**Pull request by c00ler**
…on into the docker image.

### CODE REVIEW

**Comment by danpersa** [comment]
👍

**Comment by danpersa** [comment]
I guess you also need to update/add some documentation... on how to use this...

**Comment by c00ler** [comment]
This one: https://github.com/zalando/innkeeper/blob/master/DOCKER.md ?

**Comment by danpersa** [comment]
looks like a good place :)

**Comment by danpersa** [comment]
Closes #93

**Pull request merged**
